[package]
name = "rust_raspberry_pi_zero_w"
version = "0.1.0"
authors = ["Youngermaster <juanmanuel12.13jmyh81@gmail.com>"]
edition = "2018"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"

[dependencies]
